[workspace]
members = [
    "stdf-core",
    "stdf-io",
    "stdf-arrow",
    "stdf-parquet",
    "stdf-py",
    "stdf-cli",
    "stdf-validate",
    "stdf-ascii",
    "stdf-analytics",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
thiserror = "2"
arrow = { version = "55" }
parquet = { version = "55", features = ["arrow"] }
pyo3 = { version = "0.24.1", features = ["extension-module"] }
memmap2 = "0.9"
clap = { version = "4", features = ["derive"] }
rayon = "1.10"
flate2 = "1"
criterion = { version = "0.5", features = ["html_reports"] }

